[build]
  command = "gatsby build"
  publish = "public/"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://trusting-leavitt-f25c74.netlify.com/*"
  to = "https://guide.infinitybots.xyz/:splat"
  status = 301
  force = true

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "http://guide.infinitybots.xyz/:splat"
  to = "https://guide.infinitybots.xyz/:splat"
  status = 301
  force = true